global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'team20_app_metrics'
    static_configs:
      - targets:
          - 'team20_api_product:8000'     # API product app metrics
          - 'team20_local_product:8000'   # Local product app metrics

  - job_name: 'team20_node_exporter'
    static_configs:
      - targets:
          - 'team20_api_product:9100'     # API product system metrics
          - 'team20_local_product:9100'   # Local product system metrics
